version: '3.3'
services:
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_DB: 'huoshui'
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: 'paladinze'
      # You can use whatever password you like
      POSTGRES_PASSWORD: '921021'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '5432:5432'
    expose:
      # Opens port 3306 on the container
      - '5432'
      # Where our data will be persisted
    volumes:
      - postgres_data:/var/lib/postgresql/data 
# Names our volume
volumes:
  postgres_data: